services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/shortner
    depends_on:
      - mongodb
    restart: unless-stopped
    networks:
      - url-shortener-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=shortner
    restart: unless-stopped
    networks:
      - url-shortener-network

networks:
  url-shortener-network:
    driver: bridge

volumes:
  mongodb_data: